### ISSUE TITLE
It would be better to set relative search path in Podfile

### ISSUE THREAD

**Issue by Jerome1210** [Insofan/HXFloatingHearts#1]
change   
`pod 'HXFloatingHearts', :path => '/haixiao/Desktop/OCDevelopment/HXFloatingHearts'`
into   
`pod 'HXFloatingHearts', :path => '../'`
would be much friendly

**Comment by Insofan** [comment]
THX for your tips

**Comment by ARGAMX** [comment]
still not working.
 pod 'HXFloatingHearts', :path => '/Users/haixiao/Desktop/OCDevelopment/HXFloatingHearts'
in podfile.

**Comment by Insofan** [comment]
@ARGAMX sorry, i havent log in github for 4 month ,I will do my best to fix it.
